### ISSUE TITLE
Program don't store/load custom settings

### ISSUE THREAD

**Issue by GuidoFe** [gisodal/cumodoro#3]
When I modify the pomodoro time (or break time), it remains modified in Settings windows for the entire session, but every time a new pomodoro begins, time is reset to 25:00 (even if in setting window the pomodoro time is still modified). Log file in ~/.cumodoro is empty. I leave in attachment my data.db file.
[data.db.zip](https://github.com/gisodal/cumodoro/files/1126128/data.db.zip)

**Comment by gisodal** [comment]
There was a typo in the section editting the configuration. I fixed that now. The timer resets to the new time after countdown. You can also edit the timer manually if you want to use the new time immediately (press enter at the timer window).
